version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-delivery-dev01
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery
    networks:
      - delivery-net

  delivery-app:
    image: nkantartzopoulos/delivery-app:dev01
    container_name: delivery-app-dev01
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/delivery
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    networks:
      - delivery-net

networks:
  delivery-net:
