services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "7902:9090"
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "7903:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  postgres-db:
    image: postgres
    container_name: postgres-delivery-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delivery
    volumes:
      - deliveryPSQL:/var/lib/postgresql/data
    ports:
      - "7904:5432"
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  monitoring:

volumes:
  deliveryPSQL:
