services:
  postgres-db:
    image: postgres
    container_name: postgres-delivery-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delivery
    volumes:
      - deliveryPSQL:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  monitoring:

volumes:
  deliveryPSQL:
