tunnel: the-tunnel-uuid
credentials-file: /home/nik/.cloudflared/the-tunnel-uuid.json

ingress:
  # 🌐 Frontend environments
  - hostname: delivery-dev01.rtlan.gr
    service: http://localhost:30101

  - hostname: delivery-dev02.rtlan.gr
    service: http://localhost:30102

  - hostname: delivery-dev03.rtlan.gr
    service: http://localhost:30103

  - hostname: delivery-sit01.rtlan.gr
    service: http://localhost:30111

  - hostname: delivery.rtlan.gr
    service: http://localhost:30121

  # ⚙️ Backend / API services
  - hostname: be-delivery-dev01.rtlan.gr
    service: http://localhost:30201
    originRequest:
      http2Origin: false

  - hostname: be-delivery-dev02.rtlan.gr
    service: http://localhost:30202
    originRequest:
      http2Origin: false

  - hostname: be-delivery-dev03.rtlan.gr
    service: http://localhost:30203
    originRequest:
      http2Origin: false

  - hostname: be-delivery-sit04.rtlan.gr
    service: http://localhost:30211
    originRequest:
      http2Origin: false

  - hostname: be-delivery.rtlan.gr
    service: http://localhost:30221
    originRequest:
      http2Origin: false

  # 📊 Prometheus (per environment)
  - hostname: prometheus-delivery-dev01.rtlan.gr
    service: http://localhost:30301
    originRequest:
      http2Origin: false

  - hostname: prometheus-delivery-dev02.rtlan.gr
    service: http://localhost:30302
    originRequest:
      http2Origin: false

  - hostname: prometheus-delivery-dev03.rtlan.gr
    service: http://localhost:30303
    originRequest:
      http2Origin: false

  - hostname: prometheus-delivery-sit01.rtlan.gr
    service: http://localhost:30311
    originRequest:
      http2Origin: false

  - hostname: prometheus-delivery.rtlan.gr
    service: http://localhost:30321
    originRequest:
      http2Origin: false

  # 📊 Grafana dashboards (per environment)
  - hostname: grafana-delivery-dev01.rtlan.gr
    service: http://localhost:30401
    originRequest:
      http2Origin: false

  - hostname: grafana-delivery-dev02.rtlan.gr
    service: http://localhost:30402
    originRequest:
      http2Origin: false

  - hostname: grafana-delivery-dev03.rtlan.gr
    service: http://localhost:30403
    originRequest:
      http2Origin: false

  - hostname: grafana-delivery-sit01.rtlan.gr
    service: http://localhost:30411
    originRequest:
      http2Origin: false

  - hostname: grafana-delivery.rtlan.gr
    service: http://localhost:30421
    originRequest:
      http2Origin: false

  # 🛑 Default catch-all
  - service: http_status:404
