name: Check build

on:
  push:
    branches: [ main ]

jobs:
  check-commit-message:
    uses: ./.github/workflows/check-commit-message.yml

  build:
    runs-on: ubuntu-latest
    needs: check-commit-message

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build
