name: Check Commit Message

on:
  workflow_call:

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(Github|Docker|Gradle|Spring|Pitstop|Fix|Tests|K8s|Helm|Frontend|Deploy|Guide|Metrics|Prometheus|Grafana):\s.*'
          error: "❌ Invalid format: commit message must start with one of [Github, Docker, Gradle, Spring, Pitstop, Fix, Tests, K8s, Helm, Metrics, Prometheus, Grafana], followed by a colon and a space (e.g., Gradle: Update build logic)."
