name: Hello World!

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: | 
            echo "Hello World!"
            a=21
            echo "Value is $a"
